version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:bionic
    working_directory: /app
    steps:
      - checkout
      - run: npm install --prefix=./firebase-deploy firebase-tools
      - run: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
